import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import Wrapper from "@/components/Wrapper";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en" className="scrollbar-none scroll-smooth">
      <body className={raleway.className}>
        <Wrapper>
          <Navbar />
          <main className="mt-28 min-h-40 w-full z-0">{children}</main>
        </Wrapper>
        <div>{modal}</div>
        <Footer />
      </body>
    </html>
  );
}
